project_id = "voice-ideas"

[functions.organize]
verify_jwt = true

[functions.share-idea]
verify_jwt = false

[functions.accept-idea-invite]
verify_jwt = false

[functions.list-shared-ideas]
verify_jwt = false

[functions.transcribe]
verify_jwt = true
